name: Build Blockera Plugin Tests

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]

    workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build_tests:
        name: Building and Run E2E Tests
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'blockeraai/blockera-pro' || github.event_name == 'pull_request' }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Find Specs Files
              id: find_specs_files
              run: echo "file_count=$(find ./packages -name "*.build.e2e.cy.js" | wc -l)" >> $GITHUB_OUTPUT

            - name: Setup Node.js and install dependencies
              # Only run if Specs files are found.
              if: steps.find_specs_files.outputs.file_count != '0'
              uses: ./.github/setup-node

            - name: Install Composer dependencies
              # Only run if Specs files are found.
              if: steps.find_specs_files.outputs.file_count != '0'
              uses: ramsey/composer-install@v2
              with:
                  custom-cache-suffix: $(/bin/date -u --date='last Mon' "+%F")
                  composer-options: '--no-dev -o --apcu-autoloader -a'

            - name: Build Plugin Zip File
              # Only run if Specs files are found.
              if: steps.find_specs_files.outputs.file_count != '0'
              uses: ./.github/build-plugin-zip

            - name: Extract blockera-pro.zip to build directory
              # Only run if Specs files are found.
              if: steps.find_specs_files.outputs.file_count != '0'
              run: |
                  mkdir build
                  unzip blockera-pro.zip -d ./build/blockera-pro
                  rm -rf blockera-pro.zip

            - name: Create Requirements
              # Only run if Specs files are found.
              if: steps.find_specs_files.outputs.file_count != '0'
              run: |
                  cd ./build/blockera-pro
                  mkdir packages
                  mkdir packages/blockera-pro
                  mkdir packages/blockera-pro/tests
                  cd ../..
                  node .github/scripts/create-wp-env.js "general"
                  cat .wp-env.json
                  touch cypress.env.json
                  echo '{"isLogin": false,"wpUsername": "admin","wpPassword": "password","testURL": "http://localhost:8888","e2e": {"excludeSpecPattern": [],"specPattern": ["packages/**/*.build.e2e.cy.js"]}}' >> cypress.env.json
                  cat cypress.env.json
                  cp ./package.json ./build/blockera-pro
                  cp -r ./node_modules ./build/blockera-pro
                  cp ./cypress.config.js ./build/blockera-pro
                  cp .wp-env.json ./build/blockera-pro
                  cp -r ./packages/dev-cypress ./build/blockera-pro/packages
                  find ./packages -path "*-pro*" -name "*.build.e2e.cy.js" -type f -exec cp {} ./build/blockera-pro/packages/blockera-pro/tests \;

            - name: Setup and Run E2E tests on Blockera build
              # Only run if Specs files are found.
              if: steps.find_specs_files.outputs.file_count != '0'
              run: |
                  cd ./build/blockera-pro
                  npx cypress install
                  npm run env:start
                  npm run test:e2e
                  npm run env:stop
