name: Cypress Components Tests

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    cypress_components_tests:
        name: Cypress Components Tests
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'blockeraai/blockera-pro' || github.event_name == 'pull_request' }}
        env:
            BLOCKERA_GLOBAL_PACKAGES_TOKEN: ${{ secrets.BLOCKERABOT_PAT }}
            BLOCKERA_CT_SKIP_IF_NO_SPECS: 'true'
            BLOCKERA_CT_SPECS_ROOTS: ./packages/blockera-pro-* ./packages/*-pro
            BLOCKERA_CT_COMPOSER_INSTALL: 'false'
            BLOCKERA_CT_BUILD: 'false'
            BLOCKERA_CT_TEST_CMD: npm run test:ct -- --spec "./packages/blockera-pro-*/**/*.component.cy.js" "./packages/*-pro/**/*.component.cy.js"
        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.BLOCKERABOT_PAT }}

            - name: Ensure global-packages submodule
              uses: ./.github/actions/ensure-global-packages

            - uses: ./packages/global-packages/packages/dev-tools/github/actions/setup-node

            - run: bash packages/global-packages/packages/dev-tools/github/scripts/jobs/cypress-components-tests/run.sh
