name: Plugin Compatibility Test

on:
    pull_request:
    push:
        branches: [master]
    workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test:
        name: Run Plugin Compatibility Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Setup PHP Composer and install dependencies
              uses: ./.github/setup-php
              with:
                  custom-cache-suffix: $(/bin/date -u --date='last Mon' "+%F")
                  composer-options: '--no-dev -o --apcu-autoloader -a'

            - name: Build Plugin
              uses: ./.github/build-plugin-zip

            - name: Create required environment files
              run: |
                  # Get one left until last release version from Blockera repo
                  BLOCKERA_DOWNLOAD_URL=$(curl -s https://api.github.com/repos/blockeraai/blockera/releases | jq -r '.[1].assets[0].browser_download_url')
                  echo "Latest Blockera version: $BLOCKERA_DOWNLOAD_URL"

                  # Create wp-env config with version
                  node .github/scripts/create-wp-env.js "general" "$BLOCKERA_DOWNLOAD_URL"
                  cat .wp-env.json

                  # Create env file
                  touch .env
                  echo APP_MODE=production >> .env
                  echo DB=wp_tests >> .env 
                  echo CI_ENV=true >> .env
                  cat .env

            - name: Setup WP Environment
              run: |
                  npm run env:start

            - name: Run e2e tests
              run: |
                  # Run only plugin compatibility tests
                  npm run test:e2e -- --spec "packages/(blockera-pro-**|**-pro)/**/*.plugin-compatibility.e2e.cy.js"

            - name: Stop WP Environment
              if: always()
              run: npm run env:stop
