name: Check Blockera (pro) Compatibility With Blockera (free)

on:
    pull_request:
    push:
        branches: [master]
    workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test:
        name: Run Plugin Compatibility Tests
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                strategy:
                    [
                        blockera-free-previous,
                        blockera-free-latest,
                        blockera-pro-previous,
                    ]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Install Cypress
              run: npx cypress install

            - name: Setup PHP Composer and install dependencies
              uses: ./.github/setup-php
              with:
                  custom-cache-suffix: $(/bin/date -u --date='last Mon' "+%F")
                  composer-options: '--no-dev -o --apcu-autoloader -a'

            - name: Build Plugin
              uses: ./.github/build-plugin-zip

            - name: Create required environment files
              run: |
                  # Get Blockera version based on strategy
                  if [ "${{ matrix.strategy }}" = "blockera-free-previous" ]; then
                    # Get previous supported version (index -1)
                    BLOCKERA_DOWNLOAD_URL=$(curl -s https://api.github.com/repos/blockeraai/blockera/releases | jq -r '.[-1].assets[0].browser_download_url')
                  elif [ "${{ matrix.strategy }}" = "blockera-free-latest" ]; then
                    # Get latest version (index 0) 
                    BLOCKERA_DOWNLOAD_URL=$(curl -s https://api.github.com/repos/blockeraai/blockera/releases | jq -r '.[0].assets[0].browser_download_url')
                  fi

                  echo "Using Blockera version: $BLOCKERA_DOWNLOAD_URL"

                  # Create wp-env config with version
                  node .github/scripts/create-wp-env.js "general" "$BLOCKERA_DOWNLOAD_URL"
                  cat .wp-env.json

                  # Create env file
                  touch .env
                  echo APP_MODE=production >> .env
                  echo DB=wp_tests >> .env 
                  echo CI_ENV=true >> .env
                  cat .en

                  if [ "${{ matrix.strategy }}" = "blockera-pro-previous" ]; then
                    # Get current version from blockera-pro.php
                    CURRENT_VERSION=$(grep "Version:" blockera-pro.php | awk '{print $2}')
                    echo "Current version: $CURRENT_VERSION"
                    
                    # Decrease patch version by 1
                    NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF=$NF-1;}1' OFS=.)
                    echo "New version: $NEW_VERSION"
                    
                    # Update version in blockera-pro.php
                    sed -i "s/Version: $CURRENT_VERSION/Version: $NEW_VERSION/" blockera-pro.php
                  fi

            - name: Setup WP Environment
              run: |
                  npm run env:start

            - name: Run e2e tests
              run: |
                  # Run only plugin compatibility tests
                  npm run test:e2e -- --spec "packages/(blockera-pro-**|**-pro)/**/*.plugin-compatibility.e2e.cy.js"

            - name: Stop WP Environment
              if: always()
              run: npm run env:stop
